export function mean(values: number[]): number | undefined { const v = values.filter(Number.isFinite); return v.length ? v.reduce((a, b) => a + b, 0) / v.length : undefined; }
export function median(values: number[]): number | undefined { const v = values.filter(Number.isFinite).sort((a, b) => a - b); if (!v.length) return undefined; const m = Math.floor(v.length / 2); return v.length % 2 ? v[m] : ((v[m - 1] ?? 0) + (v[m] ?? 0)) / 2; }
export function min(values: number[]): number | undefined { const v = values.filter(Number.isFinite); return v.length ? Math.min(...v) : undefined; }
export function max(values: number[]): number | undefined { const v = values.filter(Number.isFinite); return v.length ? Math.max(...v) : undefined; }
export function standardDeviation(values: number[]): number { const avg = mean(values) ?? 0; return Math.sqrt(values.reduce((sum, value) => sum + (value - avg) ** 2, 0) / Math.max(1, values.length)); }
export function coefficientOfVariation(values: number[]): number { const avg = Math.abs(mean(values) ?? 0); return avg ? standardDeviation(values) / avg : 0; }
export function linearSlope(values: number[]): number { if (values.length < 2) return 0; const xs = values.map((_, i) => i); const mx = mean(xs) ?? 0; const my = mean(values) ?? 0; const den = xs.reduce((sum, x) => sum + (x - mx) ** 2, 0); return den ? xs.reduce((sum, x, i) => sum + (x - mx) * ((values[i] ?? 0) - my), 0) / den : 0; }
export function movingAverage(values: number[], window: number): number[] { return values.map((_, i) => mean(values.slice(Math.max(0, i - window + 1), i + 1)) ?? values[i]!); }
export function iqrOutliers(values: number[]): number[] { const sorted = values.filter(Number.isFinite).sort((a, b) => a - b); const q1 = median(sorted.slice(0, Math.floor(sorted.length / 2))) ?? 0; const q3 = median(sorted.slice(Math.ceil(sorted.length / 2))) ?? 0; const iqr = q3 - q1; return sorted.filter((value) => value < q1 - 1.5 * iqr || value > q3 + 1.5 * iqr); }
export function monotone(values: number[]): "increasing" | "decreasing" | "constant" | "mixed" { if (values.every((v) => v === values[0])) return "constant"; if (values.every((v, i) => i === 0 || v >= values[i - 1]!)) return "increasing"; if (values.every((v, i) => i === 0 || v <= values[i - 1]!)) return "decreasing"; return "mixed"; }
export function absoluteDelta(first?: number, latest?: number): number | undefined { return first === undefined || latest === undefined ? undefined : latest - first; }
export function relativeDelta(first?: number, latest?: number): number | undefined { return first === undefined || latest === undefined || first === 0 ? undefined : (latest - first) / first; }