import { issue, type SeoIssue } from "../core/issue.js";
import type { PerformanceResult } from "../performance/performance-schema.js";
import { defaultPerformanceThresholds, scorePerformance } from "../performance/performance-scoring.js";

function perfIssue(input: { id: string; severity: "info" | "low" | "medium" | "high" | "critical"; title: string; description: string; recommendation: string; result: PerformanceResult; value?: number; threshold?: number }): SeoIssue {
  return issue({ id: input.id, category: "performance", severity: input.severity, title: input.title, description: input.description, recommendation: input.recommendation, affectedUrl: input.result.finalUrl ?? input.result.url, evidence: { source: input.result.source, engine: input.result.engine, scoreKind: input.result.scoreKind, scope: input.result.scope, device: input.result.device, value: input.value, threshold: input.threshold, confidence: input.result.confidence } });
}

export function analyzePerformanceResults(results: PerformanceResult[]): SeoIssue[] {
  const issues: SeoIssue[] = [];
  for (const result of results) {
    if (result.error) {
      issues.push(perfIssue({ id: "performance.adapter-unavailable", severity: "info", title: "Performance adapter unavailable", description: "A performance data source failed or returned partial data.", recommendation: "Retry later or check adapter credentials/network availability.", result }));
      continue;
    }
    const score = scorePerformance(result);
    if (score < 50) issues.push(perfIssue({ id: "performance.low-score", severity: "high", title: "Low performance score", description: "The normalized performance score is below the recommended range.", recommendation: "Prioritize LCP, blocking JavaScript, resource weight, and server response time improvements.", result, value: score, threshold: 50 }));
    if (result.metrics.lcpMs && result.metrics.lcpMs > defaultPerformanceThresholds.lcpGoodMs) issues.push(perfIssue({ id: "performance.slow-lcp", severity: result.metrics.lcpMs > defaultPerformanceThresholds.lcpPoorMs ? "high" : "medium", title: "Largest Contentful Paint is slow", description: "LCP exceeds the Core Web Vitals good threshold.", recommendation: "Optimize hero image delivery, preload critical resources, reduce server time, and remove render blocking work.", result, value: result.metrics.lcpMs, threshold: defaultPerformanceThresholds.lcpGoodMs }));
    if (result.metrics.inpMs && result.metrics.inpMs > defaultPerformanceThresholds.inpGoodMs) issues.push(perfIssue({ id: "performance.slow-inp", severity: result.metrics.inpMs > defaultPerformanceThresholds.inpPoorMs ? "high" : "medium", title: "Interaction to Next Paint is slow", description: "Field INP exceeds the Core Web Vitals good threshold.", recommendation: "Reduce JavaScript, split long tasks, defer non-critical scripts, and audit third-party work.", result, value: result.metrics.inpMs, threshold: defaultPerformanceThresholds.inpGoodMs }));
    if (result.metrics.cls && result.metrics.cls > defaultPerformanceThresholds.clsGood) issues.push(perfIssue({ id: "performance.high-cls", severity: result.metrics.cls > defaultPerformanceThresholds.clsPoor ? "high" : "medium", title: "Cumulative Layout Shift is high", description: "CLS exceeds the Core Web Vitals good threshold.", recommendation: "Reserve image and ad space, define media dimensions, manage font loading, and avoid late layout injections.", result, value: result.metrics.cls, threshold: defaultPerformanceThresholds.clsGood }));
    if (result.metrics.tbtMs && result.metrics.tbtMs > defaultPerformanceThresholds.tbtGoodMs) issues.push(perfIssue({ id: "performance.high-tbt", severity: result.metrics.tbtMs > defaultPerformanceThresholds.tbtPoorMs ? "high" : "medium", title: "Total Blocking Time is high", description: "Local lab TBT is high. TBT is not the same as field INP.", recommendation: "Reduce JavaScript execution, split long tasks, code split bundles, and defer non-critical scripts.", result, value: result.metrics.tbtMs, threshold: defaultPerformanceThresholds.tbtGoodMs }));
    if (result.metrics.ttfbMs && result.metrics.ttfbMs > defaultPerformanceThresholds.ttfbGoodMs) issues.push(perfIssue({ id: "performance.slow-ttfb", severity: result.metrics.ttfbMs > defaultPerformanceThresholds.ttfbPoorMs ? "high" : "medium", title: "Server response time is slow", description: "TTFB exceeds the recommended lab threshold.", recommendation: "Use server caching, CDN delivery, backend optimization, compression, and reduce redirects.", result, value: result.metrics.ttfbMs, threshold: defaultPerformanceThresholds.ttfbGoodMs }));
    const transfer = result.resources?.transferBytes ?? 0;
    if (transfer > 2500000) issues.push(perfIssue({ id: "performance.excessive-page-weight", severity: "medium", title: "Page transfer size is excessive", description: "Total transferred bytes are high.", recommendation: "Compress assets, remove unused code, optimize images, and ship smaller bundles.", result, value: transfer, threshold: 2500000 }));
    if ((result.resources?.javascriptBytes ?? 0) > 700000) issues.push(perfIssue({ id: "performance.excessive-javascript", severity: "medium", title: "JavaScript weight is excessive", description: "JavaScript bytes are high for this page.", recommendation: "Split bundles, tree-shake dependencies, defer non-critical scripts, and reduce third-party scripts.", result, value: result.resources?.javascriptBytes, threshold: 700000 }));
    if ((result.resources?.imageBytes ?? 0) > 1500000) issues.push(perfIssue({ id: "performance.excessive-images", severity: "medium", title: "Image weight is excessive", description: "Image transfer bytes are high.", recommendation: "Resize, compress, lazy-load non-critical images, and prioritize the LCP image.", result, value: result.resources?.imageBytes, threshold: 1500000 }));
    if ((result.resources?.requestCount ?? 0) > 80) issues.push(perfIssue({ id: "performance.high-request-count", severity: "low", title: "Request count is high", description: "The page makes many network requests.", recommendation: "Remove unnecessary resources and consolidate critical delivery where appropriate.", result, value: result.resources?.requestCount, threshold: 80 }));
    if ((result.diagnostics?.unusedJavascriptBytes ?? 0) > 250000) issues.push(perfIssue({ id: "performance.unused-javascript", severity: "medium", title: "Unused JavaScript is high", description: "Lighthouse detected substantial unused JavaScript bytes.", recommendation: "Use code splitting, tree shaking, defer, or remove scripts when Lighthouse provides enough evidence.", result, value: result.diagnostics?.unusedJavascriptBytes, threshold: 250000 }));
    if ((result.diagnostics?.unusedCssBytes ?? 0) > 100000) issues.push(perfIssue({ id: "performance.unused-css", severity: "low", title: "Unused CSS is high", description: "Lighthouse detected unused CSS bytes.", recommendation: "Purge unused CSS and consider critical CSS extraction.", result, value: result.diagnostics?.unusedCssBytes, threshold: 100000 }));
    if ((result.diagnostics?.renderBlockingResources ?? 0) > 0) issues.push(perfIssue({ id: "performance.render-blocking-resources", severity: "medium", title: "Render-blocking resources detected", description: "Lighthouse found resources that can block first render.", recommendation: "Inline critical CSS, preload critical resources, and defer non-critical blocking resources.", result, value: result.diagnostics?.renderBlockingResources, threshold: 0 }));
    if ((result.diagnostics?.longTaskCount ?? 0) > 0) issues.push(perfIssue({ id: "performance.long-tasks", severity: "medium", title: "Long main-thread tasks detected", description: "Lighthouse or local metrics detected long tasks.", recommendation: "Split long tasks, reduce JavaScript execution, and inspect scripts identified by Lighthouse.", result, value: result.diagnostics?.longTaskCount, threshold: 0 }));    if (result.warnings.some((warning) => /variance/i.test(warning))) issues.push(perfIssue({ id: "performance.high-variance", severity: "low", title: "Performance measurements have high variance", description: "Multiple local runs varied significantly.", recommendation: "Repeat measurements and inspect unstable network or runtime conditions before making release decisions.", result }));
  }
  return issues;
}
